name: Backend Docker Build
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker Image
        run: |
          # بناء الصورة من الفولدر الحالي
          docker build -t backend-image:latest .

      - name: Run Server to Connect to MongoDB
        run: |
          # تشغيل الحاوية في الخلفية
          docker run -d --name test-container backend-image:latest
          # الانتظار 30 ثانية للتأكد من إتمام الاتصال بمونجو
          sleep 30
          # عرض سجلات السيرفر عشان نتأكد إنه قال "تم الاتصال"
          docker logs test-container
          # إيقاف الحاوية بعد إتمام المهمة
          docker stop test-container